<?php include $phireHeader; ?>
    <h1 class="seo-header"><?=$title; ?></h1>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/seo">Back</a></nav>
    </nav>
    <form id="seo-form" action="<?=$phireUri . '/seo/analysis'; ?>" method="post">
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th>&nbsp;</th>
            </tr>
<?php if (count($seoAnalysis) > 0): ?>
            <tr>
                <td>Got some!</td>
            </tr>
<?php else: ?>
            <tr>
                <td><p style="padding: 20px;">The SEO analysis has not been processed yet.</p></td>
            </tr>
<?php endif; ?>
        </table>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Process" /></div>
    </form>
<?php include $phireFooter; ?>