<?php include $phireHeader; ?>
    <h1 class="seo-header"><?=$title; ?></h1>
    <form id="seo-form" action="<?=$phireUri . '/seo'; ?>" method="post">
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th>Google Analytics</th>
            </tr>
            <tr>
                <td><textarea id="seo_ga" name="seo_ga" rows="10" cols="40"><?=htmlentities($seoConfig['ga'], ENT_QUOTES, 'UTF-8'); ?></textarea></td>
            </tr>
            <tr>
                <th>Default Meta Tags</th>
            </tr>
<?php foreach ($seoConfig['meta'] as $key => $meta): ?>
            <tr>
                <td><input name="meta_name_<?=($key + 1); ?>" type="text" class="meta-name-field" size="25" value="<?=htmlentities($meta['name'], ENT_QUOTES, 'UTF-8'); ?>" placeholder="Name" /> <input name="meta_content_<?=($key + 1); ?>" type="text" class="meta-content-field" size="50" value="<?=htmlentities($meta['content'], ENT_QUOTES, 'UTF-8'); ?>" placeholder="Content" /></td>
            </tr>
<?php endforeach; ?>
            <tr>
                <td><input name="meta_name_new" type="text" class="meta-name-field" size="25" value="" placeholder="name" /> <input name="meta_content_new" type="text" class="meta-content-field" size="50" value="" placeholder="content" /></td>
            </tr>
        </table>
        <div id="form-footer"><input type="submit" name="submit" class="save-btn" value="Save" /></div>
    </form>
<?php include $phireFooter; ?>